name: AI Shorts Generator


on:

  workflow_dispatch:

  schedule:

    - cron: "0 9 * * *"
    - cron: "0 15 * * *"
    - cron: "0 21 * * *"
  
jobs:

  generate:

    runs-on: ubuntu-latest

    timeout-minutes: 30


    steps:


      # ==========================
      # DOWNLOAD PROJECT
      # ==========================

      - name: Download project

        uses: actions/checkout@v4


      # ==========================
      # PYTHON
      # ==========================

      - name: Install Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.11"

          cache: "pip"


      # ==========================
      # FFMPEG
      # ==========================

      - name: Install ffmpeg

        run: |

          sudo apt-get update

          sudo apt-get install -y ffmpeg


      # ==========================
      # WHISPER CACHE
      # ==========================

      - name: Cache Whisper model

        uses: actions/cache@v4

        with:

          path: ~/.cache/whisper

          key: whisper-tiny-v1


      # ==========================
      # PYTHON PACKAGES
      # ==========================

      - name: Install packages

        run: |

          python -m pip install --upgrade pip

          pip install -r requirements.txt


      # ==========================
      # RUN AI SHORTS GENERATOR
      # ==========================

      - name: Run AI

        env:

          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}

          PEXELS_KEY: ${{ secrets.PEXELS_KEY }}

          FREESOUND_API_KEY: ${{ secrets.FREESOUND_API_KEY }}

          YOUTUBE_TOKEN: ${{ secrets.YOUTUBE_TOKEN }}


        run: |

          python main.py


      # ==========================
      # SAVE VIDEO AND THUMBNAIL
      # ==========================

      - name: Save generated files

        uses: actions/upload-artifact@v4

        with:

          name: youtube-short

          path: |

            output/short.mp4

            output/thumbnail.jpg

          if-no-files-found: error
