name: AI Shorts Generator

on:

  workflow_dispatch:

  schedule:

    - cron: "0 9 * * *"


jobs:

  generate:

    runs-on: ubuntu-latest


    steps:

    - name: Download project

      uses: actions/checkout@v4


    - name: Install Python

      uses: actions/setup-python@v5

      with:

        python-version: "3.11"


    - name: Install ffmpeg

      run: |

        sudo apt-get update

        sudo apt-get install -y ffmpeg


    - name: Install packages

      run: |

        pip install -r requirements.txt


    - name: Create YouTube token

      env:

        YOUTUBE_TOKEN: ${{ secrets.YOUTUBE_TOKEN }}

      run: |

        echo "$YOUTUBE_TOKEN" > token.json


    - name: Run AI

      env:

        GEMINI_KEY: ${{ secrets.GEMINI_KEY }}

        PEXELS_KEY: ${{ secrets.PEXELS_KEY }}

        FREESOUND_API_KEY: ${{ secrets.FREESOUND_API_KEY }}


      run:

        python main.py


    - name: Save video

      uses: actions/upload-artifact@v4

      with:

        name: youtube-short

        path: output/short.mp4
